//
//  Rates.h
//  AiWars
//
//  Created by Ted McCormack on 4/16/09.
//  Copyright 2009 Slyco. All rights reserved.
//

#import <Foundation/Foundation.h>

#define CYCLES_PER_SECOND		30.0
#define INCREMENT_PER_CYCLE		(1.0/CYCLES_PER_SECOND)

#define MAX_JAMMED_TIME			(90.0/CYCLES_PER_SECOND)
#define MAX_ICY_TIME			(90.0/CYCLES_PER_SECOND)
#define MAX_FIRE_TIME			(90.0/CYCLES_PER_SECOND)
#define MAX_TURN_RATE			(300.0/CYCLES_PER_SECOND)
#define TARGET_CHANGE_DELAY		(35.0/CYCLES_PER_SECOND)
#define FORCE_CONSTANT			(1.0/(100.0*CYCLES_PER_SECOND))

#define NORMAL_ATTACK_RATE		(20.0/CYCLES_PER_SECOND)
#define NORMAL_WEAPON_SPEED		(2.0/CYCLES_PER_SECOND)

#define MISSILE_ATTACK_RATE		(60.0/CYCLES_PER_SECOND)
#define MISSILE_WEAPON_SPEED	(1.5/CYCLES_PER_SECOND)

#define LASER_ATTACK_RATE		(70.0/CYCLES_PER_SECOND)
#define LASER_WEAPON_SPEED		(3.0/CYCLES_PER_SECOND)

#define RAMMER_ATTACK_RATE		(5.0/CYCLES_PER_SECOND)
#define RAMMER_WEAPON_SPEED		0

#define JAMMER_ATTACK_RATE		(200.0/CYCLES_PER_SECOND)
#define JAMMER_WEAPON_SPEED		0

#define SUICIDE_ATTACK_RATE		(1.0/CYCLES_PER_SECOND)
#define SUICIDE_WEAPON_SPEED	0

#define FLAMETHROWER_ATTACK_RATE	(90.0/CYCLES_PER_SECOND)
#define FLAMETHROWER_WEAPON_SPEED	(1.5/CYCLES_PER_SECOND)

#define LIGHTNING_ATTACK_RATE		(85.0/CYCLES_PER_SECOND)

#define PLASMA_ATTACK_RATE			(LASER_ATTACK_RATE)
#define PLASMA_WEAPON_SPEED			(2.0/CYCLES_PER_SECOND)

#define MASS_DRIVER_ATTACK_RATE		(60.0/CYCLES_PER_SECOND)
#define MASS_DRIVER_WEAPON_SPEED	(1.4/CYCLES_PER_SECOND)

#define MINE_LAYER_ATTACK_RATE		(80.0/CYCLES_PER_SECOND)
#define MINE_LAYER_WEAPON_SPEED		0

#define ICY_ATTACK_RATE				FLAMETHROWER_ATTACK_RATE

#define DEATH_RAY_ATTACK_RATE		(60.0/CYCLES_PER_SECOND)

#define FATMAN_ATTACK_RATE			(100.0/CYCLES_PER_SECOND)
#define FATMAN_WEAPON_SPEED			(0.8/CYCLES_PER_SECOND)
#define FATMAN_EXPLOSION_TIME		(2.0*CYCLES_PER_SECOND)

#define NORMAL_BOT_MOVEMENT_RATE			(0.2/CYCLES_PER_SECOND)
#define NORMAL_JAMMER_BOT_MOVEMENT_RATE		(0.2/CYCLES_PER_SECOND)
#define MISSILE_BOT_MOVEMENT_RATE			(0.1/CYCLES_PER_SECOND)
#define LASER_BOT_MOVEMENT_RATE				(0.1/CYCLES_PER_SECOND)
#define RAMMER_BOT_MOVEMENT_RATE			(0.4/CYCLES_PER_SECOND)
#define RAMMER_JAMMER_BOT_MOVEMENT_RATE		(0.4/CYCLES_PER_SECOND)
#define SUICIDE_BOT_MOVEMENT_RATE			(0.4/CYCLES_PER_SECOND)
#define FLAMETHROWER_BOT_MOVEMENT_RATE		(0.4/CYCLES_PER_SECOND)
#define LIGHTNING_BOT_MOVEMENT_RATE			(0.4/CYCLES_PER_SECOND)


