//
//  Types.h
//  AiWars
//
//  Created by Ted McCormack on 3/27/09.
//  Copyright 2009 Slyco. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef enum GameMode
{
	GAME_MODE_NONE,
	GAME_MODE_SELECT,
	GAME_MODE_BATTLE,
	GAME_MODE_BATTLE_FINISHED
} GameMode;

typedef enum GameType
{
	GAME_TYPE_NONE,
	GAME_TYPE_SINGLEPLAYER,
	GAME_TYPE_BONUS_LEVEL,
	GAME_TYPE_MULTIPLAYER,
} GameType;

typedef enum RoundType
{
	ROUND_TYPE_1 = 1,
	ROUND_TYPE_2,
	ROUND_TYPE_5,
	ROUND_TYPE_10,
	ROUND_TYPE_INF
} RoundType;

typedef enum AttackType
{
	ATTACK_TYPE_NORMAL = 0,
	ATTACK_TYPE_NORMAL_DOUBLE,
	ATTACK_TYPE_SHOTTIE,
	ATTACK_TYPE_MISSILE,
	ATTACK_TYPE_LASER,
	ATTACK_TYPE_MINE_LAYER,
	ATTACK_TYPE_MASS_DRIVER,
	ATTACK_TYPE_SUICIDE,
	ATTACK_TYPE_JAMMER,
	ATTACK_TYPE_RAMMER, 
	ATTACK_TYPE_MISSILE_DOUBLE,
	ATTACK_TYPE_SEEKING_MISSILE,
	ATTACK_TYPE_LASER_DOUBLE,
	ATTACK_TYPE_SEEKING_MISSILE_DOUBLE,
	ATTACK_TYPE_ICY,
	ATTACK_TYPE_FLAMETHROWER,
	ATTACK_TYPE_PLASMA_CANNON,
	ATTACK_TYPE_LIGHTNING,
	ATTACK_TYPE_PLASMA_CANNON_DOUBLE, 
	ATTACK_TYPE_DEATH_RAY,
	ATTACK_TYPE_FATMAN,
	NUM_ATTACK_TYPES
} AttackType;


#define MOVEMENT_TYPE_NUM		6

//changing movementTypes must also be reflected in BotSelectorViewController.m movementTypeChanged()
typedef enum MovementType
{
	MOVEMENT_TYPE_FOLLOW_CLOSEST_FRIEND = 1, /* can't follow other CLOSEST_FRIEND bots */
/*	MOVEMENT_TYPE_FOLLOW_LOWEST_COST_FRIEND, */
	MOVEMENT_TYPE_FOLLOW_HIGHEST_COST_FRIEND,
	MOVEMENT_TYPE_FOLLOW_CLOSEST_ENEMY,
/*	MOVEMENT_TYPE_FOLLOW_LOWEST_COST_ENEMY,*/
	MOVEMENT_TYPE_FOLLOW_HIGHEST_COST_ENEMY,
	MOVEMENT_TYPE_FOLLOW_LOWEST_LIFE_ENEMY,
/*	MOVEMENT_TYPE_FOLLOW_HIGHEST_LIFE_ENEMY,*/
	MOVEMENT_TYPE_RANDOM
} MovementType;

typedef enum BotType
{
	//tier 1
	BOT_TYPE_SINGLE_SHOOTER_TIER_1 = 0, //0
	BOT_TYPE_DUAL_SHOOTER_TIER_1,		//1
	BOT_TYPE_QUICKIE_TIER_1,			//2
	BOT_TYPE_SHOTTIE_TIER_1,			//3
	BOT_TYPE_MISSILE_TIER_1,			//4
	BOT_TYPE_LASER_TIER_1,				//5
	BOT_TYPE_RAMMER_TIER_1,				//6

	//tier 2
	BOT_TYPE_KAMIKAZE_TIER_2,			//7
	BOT_TYPE_DUAL_MISSILE_TIER_2,		//8
	BOT_TYPE_DUAL_LASER_TIER_2,			//9
	BOT_TYPE_SEEKER_TIER_2,				//10
	BOT_TYPE_MINE_LAYER_TIER_2,			//11
	BOT_TYPE_MASS_DRIVER_TIER_2,		//12
	
	//tier 3
	BOT_TYPE_ICY_TIER_3,				//13
	BOT_TYPE_FLAMETHROWER_TIER_3,		//14
	BOT_TYPE_DUAL_SEEKER_TIER_3,		//15
	BOT_TYPE_PLASMA_TIER_3,				//16
	
	//tier 4
	BOT_TYPE_LIGHTNING_TIER_4,			//17
	BOT_TYPE_DUAL_PLASMA_TIER_4,		//18
	BOT_TYPE_DEATH_TIER_4,				//19
	BOT_TYPE_FATMAN_TIER_4,				//20
	BOT_TYPE_BOSS_1_TIER_5,
	BOT_TYPE_BOSS_2_TIER_5,
	BOT_TYPE_BOSS_3_TIER_5,
	BOT_TYPE_BOSS_4_TIER_5,
	NUM_BOT_TYPES		
} BotType;
